/*
 * loom_isa_props: ISA-1 (docs/VERIFICATION.md L4).
 * GENERATED by formal/gen_isa_props.py from isa/isa.yaml (ISA version 0.4.0).
 * DO NOT EDIT.
 * SPDX-License-Identifier: Apache-2.0
 *
 * Formal only. Bound into loom_decode and loom_core; never read by synthesis
 * or by the TT flow.
 *
 * The mask/match table below is the one in isa/isa.yaml, read through
 * tools.loomisa. src/loom_decode.v is generated from the same YAML by a
 * different generator, so the properties compare two independent renderings
 * of the same source over all 2**16 words.
 *
 * 64 instructions, 49664 of 65536 words decode to one of them.
 */

`default_nettype none
module loom_isa_props (
    input wire [15:0] ir,
    input wire        is_add,
    input wire        is_sub,
    input wire        is_and,
    input wire        is_or,
    input wire        is_xor,
    input wire        is_shl,
    input wire        is_shr,
    input wire        is_ror,
    input wire        is_addi,
    input wire        is_subi,
    input wire        is_andi,
    input wire        is_ori,
    input wire        is_xori,
    input wire        is_shli,
    input wire        is_shri,
    input wire        is_cmpi,
    input wire        is_ldi,
    input wire        is_ldih,
    input wire        is_mov,
    input wire        is_not,
    input wire        is_neg,
    input wire        is_cmp,
    input wire        is_test,
    input wire        is_rev,
    input wire        is_par,
    input wire        is_swap,
    input wire        is_jmp,
    input wire        is_call,
    input wire        is_ret,
    input wire        is_halt,
    input wire        is_bz,
    input wire        is_bnz,
    input wire        is_bc,
    input wire        is_bnc,
    input wire        is_bt,
    input wire        is_bnt,
    input wire        is_djnz,
    input wire        is_jp,
    input wire        is_setp,
    input wire        is_oep,
    input wire        is_out,
    input wire        is_in,
    input wire        is_waitd,
    input wire        is_waitp,
    input wire        is_waite,
    input wire        is_waits,
    input wire        is_waitb,
    input wire        is_dly,
    input wire        is_setd,
    input wire        is_nop,
    input wire        is_push,
    input wire        is_pop,
    input wire        is_sho,
    input wire        is_shi,
    input wire        is_ldsr,
    input wire        is_stsr,
    input wire        is_crci,
    input wire        is_stcrc,
    input wire        is_csrr,
    input wire        is_csrw,
    input wire        is_clr,
    input wire        is_sig,
    input wire        is_ld,
    input wire        is_st,
    input wire        is_reserved
);

  // One bit per instruction of isa/isa.yaml: the word matches its
  // encoding. Straight from the YAML, not from the decoder.
  wire [63:0] m;
  assign m[0  ] = (ir & 16'hFE00) == 16'h0000;   // ADD
  assign m[1  ] = (ir & 16'hFE00) == 16'h0200;   // SUB
  assign m[2  ] = (ir & 16'hFE00) == 16'h0400;   // AND
  assign m[3  ] = (ir & 16'hFE00) == 16'h0600;   // OR
  assign m[4  ] = (ir & 16'hFE00) == 16'h0800;   // XOR
  assign m[5  ] = (ir & 16'hFE00) == 16'h0A00;   // SHL
  assign m[6  ] = (ir & 16'hFE00) == 16'h0C00;   // SHR
  assign m[7  ] = (ir & 16'hFE00) == 16'h0E00;   // ROR
  assign m[8  ] = (ir & 16'hFE00) == 16'h1000;   // ADDI
  assign m[9  ] = (ir & 16'hFE00) == 16'h1200;   // SUBI
  assign m[10 ] = (ir & 16'hFE00) == 16'h1400;   // ANDI
  assign m[11 ] = (ir & 16'hFE00) == 16'h1600;   // ORI
  assign m[12 ] = (ir & 16'hFE00) == 16'h1800;   // XORI
  assign m[13 ] = (ir & 16'hFE00) == 16'h1A00;   // SHLI
  assign m[14 ] = (ir & 16'hFE00) == 16'h1C00;   // SHRI
  assign m[15 ] = (ir & 16'hFE00) == 16'h1E00;   // CMPI
  assign m[16 ] = (ir & 16'hF800) == 16'h2000;   // LDI
  assign m[17 ] = (ir & 16'hF800) == 16'h2800;   // LDIH
  assign m[18 ] = (ir & 16'hFE00) == 16'h3000;   // MOV
  assign m[19 ] = (ir & 16'hFE00) == 16'h3200;   // NOT
  assign m[20 ] = (ir & 16'hFE00) == 16'h3400;   // NEG
  assign m[21 ] = (ir & 16'hFE00) == 16'h3600;   // CMP
  assign m[22 ] = (ir & 16'hFE00) == 16'h3800;   // TEST
  assign m[23 ] = (ir & 16'hFE00) == 16'h3A00;   // REV
  assign m[24 ] = (ir & 16'hFE00) == 16'h3C00;   // PAR
  assign m[25 ] = (ir & 16'hFE00) == 16'h3E00;   // SWAP
  assign m[26 ] = (ir & 16'hFC00) == 16'h4000;   // JMP
  assign m[27 ] = (ir & 16'hFC00) == 16'h4400;   // CALL
  assign m[28 ] = (ir & 16'hFC00) == 16'h4800;   // RET
  assign m[29 ] = (ir & 16'hFC00) == 16'h4C00;   // HALT
  assign m[30 ] = (ir & 16'hFF00) == 16'h5000;   // BZ
  assign m[31 ] = (ir & 16'hFF00) == 16'h5200;   // BNZ
  assign m[32 ] = (ir & 16'hFF00) == 16'h5400;   // BC
  assign m[33 ] = (ir & 16'hFF00) == 16'h5600;   // BNC
  assign m[34 ] = (ir & 16'hFF00) == 16'h5800;   // BT
  assign m[35 ] = (ir & 16'hFF00) == 16'h5A00;   // BNT
  assign m[36 ] = (ir & 16'hF800) == 16'h6000;   // DJNZ
  assign m[37 ] = (ir & 16'hF000) == 16'h7000;   // JP
  assign m[38 ] = (ir & 16'hFC00) == 16'h8000;   // SETP
  assign m[39 ] = (ir & 16'hFC00) == 16'h8400;   // OEP
  assign m[40 ] = (ir & 16'hFC00) == 16'h8800;   // OUT
  assign m[41 ] = (ir & 16'hFC00) == 16'h8C00;   // IN
  assign m[42 ] = (ir & 16'hFE00) == 16'h9000;   // WAITD
  assign m[43 ] = (ir & 16'hFE00) == 16'h9200;   // WAITP
  assign m[44 ] = (ir & 16'hFE00) == 16'h9400;   // WAITE
  assign m[45 ] = (ir & 16'hFE00) == 16'h9600;   // WAITS
  assign m[46 ] = (ir & 16'hFE00) == 16'h9800;   // WAITB
  assign m[47 ] = (ir & 16'hFE00) == 16'h9A00;   // DLY
  assign m[48 ] = (ir & 16'hFE00) == 16'h9C00;   // SETD
  assign m[49 ] = (ir & 16'hFE00) == 16'h9E00;   // NOP
  assign m[50 ] = (ir & 16'hFF80) == 16'hA000;   // PUSH
  assign m[51 ] = (ir & 16'hFF80) == 16'hA080;   // POP
  assign m[52 ] = (ir & 16'hFF80) == 16'hA400;   // SHO
  assign m[53 ] = (ir & 16'hFF80) == 16'hA480;   // SHI
  assign m[54 ] = (ir & 16'hFF80) == 16'hA800;   // LDSR
  assign m[55 ] = (ir & 16'hFF80) == 16'hA880;   // STSR
  assign m[56 ] = (ir & 16'hFF80) == 16'hAC00;   // CRCI
  assign m[57 ] = (ir & 16'hFF80) == 16'hAC80;   // STCRC
  assign m[58 ] = (ir & 16'hF800) == 16'hB000;   // CSRR
  assign m[59 ] = (ir & 16'hF800) == 16'hB800;   // CSRW
  assign m[60 ] = (ir & 16'hF800) == 16'hC000;   // CLR
  assign m[61 ] = (ir & 16'hF800) == 16'hC800;   // SIG
  assign m[62 ] = (ir & 16'hF800) == 16'hD000;   // LD
  assign m[63 ] = (ir & 16'hF800) == 16'hD800;   // ST

  // ================================================================
  // ISA-1A: every 16-bit pattern matches at most one instruction, so
  // "decodes to exactly one instruction class" holds for every word
  // that decodes at all. ($onehot0 written out, for portability.)
  // ================================================================
  always @(*) assert ((m & (m - 64'd1)) == 64'd0);

  // ================================================================
  // ISA-1B: the decoder's one-hot strobes are exactly those matches.
  // ================================================================
  always @(*) begin
    assert (is_add     == m[0]);
    assert (is_sub     == m[1]);
    assert (is_and     == m[2]);
    assert (is_or      == m[3]);
    assert (is_xor     == m[4]);
    assert (is_shl     == m[5]);
    assert (is_shr     == m[6]);
    assert (is_ror     == m[7]);
    assert (is_addi    == m[8]);
    assert (is_subi    == m[9]);
    assert (is_andi    == m[10]);
    assert (is_ori     == m[11]);
    assert (is_xori    == m[12]);
    assert (is_shli    == m[13]);
    assert (is_shri    == m[14]);
    assert (is_cmpi    == m[15]);
    assert (is_ldi     == m[16]);
    assert (is_ldih    == m[17]);
    assert (is_mov     == m[18]);
    assert (is_not     == m[19]);
    assert (is_neg     == m[20]);
    assert (is_cmp     == m[21]);
    assert (is_test    == m[22]);
    assert (is_rev     == m[23]);
    assert (is_par     == m[24]);
    assert (is_swap    == m[25]);
    assert (is_jmp     == m[26]);
    assert (is_call    == m[27]);
    assert (is_ret     == m[28]);
    assert (is_halt    == m[29]);
    assert (is_bz      == m[30]);
    assert (is_bnz     == m[31]);
    assert (is_bc      == m[32]);
    assert (is_bnc     == m[33]);
    assert (is_bt      == m[34]);
    assert (is_bnt     == m[35]);
    assert (is_djnz    == m[36]);
    assert (is_jp      == m[37]);
    assert (is_setp    == m[38]);
    assert (is_oep     == m[39]);
    assert (is_out     == m[40]);
    assert (is_in      == m[41]);
    assert (is_waitd   == m[42]);
    assert (is_waitp   == m[43]);
    assert (is_waite   == m[44]);
    assert (is_waits   == m[45]);
    assert (is_waitb   == m[46]);
    assert (is_dly     == m[47]);
    assert (is_setd    == m[48]);
    assert (is_nop     == m[49]);
    assert (is_push    == m[50]);
    assert (is_pop     == m[51]);
    assert (is_sho     == m[52]);
    assert (is_shi     == m[53]);
    assert (is_ldsr    == m[54]);
    assert (is_stsr    == m[55]);
    assert (is_crci    == m[56]);
    assert (is_stcrc   == m[57]);
    assert (is_csrr    == m[58]);
    assert (is_csrw    == m[59]);
    assert (is_clr     == m[60]);
    assert (is_sig     == m[61]);
    assert (is_ld      == m[62]);
    assert (is_st      == m[63]);
  end

  // ================================================================
  // ISA-1C: `is_reserved` is exactly "no instruction matches"
  // (SEMANTICS 9: "Any word that matches no instruction in isa.yaml
  // ... executes as NOP ... and commits BADOP[t] <= 1").
  // ================================================================
  always @(*) assert (is_reserved == (m == 64'd0));

  // ---------------------------------------- cover (anti-vacuity)
  always @(*) begin
    cover (is_reserved);
    cover (m != 64'd0);
    cover (m[0]);
    cover (m[1]);
    cover (m[2]);
    cover (m[3]);
    cover (m[4]);
    cover (m[5]);
    cover (m[6]);
    cover (m[7]);
    cover (m[8]);
    cover (m[9]);
    cover (m[10]);
    cover (m[11]);
    cover (m[12]);
    cover (m[13]);
    cover (m[14]);
    cover (m[15]);
    cover (m[16]);
    cover (m[17]);
    cover (m[18]);
    cover (m[19]);
    cover (m[20]);
    cover (m[21]);
    cover (m[22]);
    cover (m[23]);
    cover (m[24]);
    cover (m[25]);
    cover (m[26]);
    cover (m[27]);
    cover (m[28]);
    cover (m[29]);
    cover (m[30]);
    cover (m[31]);
    cover (m[32]);
    cover (m[33]);
    cover (m[34]);
    cover (m[35]);
    cover (m[36]);
    cover (m[37]);
    cover (m[38]);
    cover (m[39]);
    cover (m[40]);
    cover (m[41]);
    cover (m[42]);
    cover (m[43]);
    cover (m[44]);
    cover (m[45]);
    cover (m[46]);
    cover (m[47]);
    cover (m[48]);
    cover (m[49]);
    cover (m[50]);
    cover (m[51]);
    cover (m[52]);
    cover (m[53]);
    cover (m[54]);
    cover (m[55]);
    cover (m[56]);
    cover (m[57]);
    cover (m[58]);
    cover (m[59]);
    cover (m[60]);
    cover (m[61]);
    cover (m[62]);
    cover (m[63]);
  end

endmodule

bind loom_decode loom_isa_props u_isa_props (
    .ir(ir),
    .is_add(is_add),
    .is_sub(is_sub),
    .is_and(is_and),
    .is_or(is_or),
    .is_xor(is_xor),
    .is_shl(is_shl),
    .is_shr(is_shr),
    .is_ror(is_ror),
    .is_addi(is_addi),
    .is_subi(is_subi),
    .is_andi(is_andi),
    .is_ori(is_ori),
    .is_xori(is_xori),
    .is_shli(is_shli),
    .is_shri(is_shri),
    .is_cmpi(is_cmpi),
    .is_ldi(is_ldi),
    .is_ldih(is_ldih),
    .is_mov(is_mov),
    .is_not(is_not),
    .is_neg(is_neg),
    .is_cmp(is_cmp),
    .is_test(is_test),
    .is_rev(is_rev),
    .is_par(is_par),
    .is_swap(is_swap),
    .is_jmp(is_jmp),
    .is_call(is_call),
    .is_ret(is_ret),
    .is_halt(is_halt),
    .is_bz(is_bz),
    .is_bnz(is_bnz),
    .is_bc(is_bc),
    .is_bnc(is_bnc),
    .is_bt(is_bt),
    .is_bnt(is_bnt),
    .is_djnz(is_djnz),
    .is_jp(is_jp),
    .is_setp(is_setp),
    .is_oep(is_oep),
    .is_out(is_out),
    .is_in(is_in),
    .is_waitd(is_waitd),
    .is_waitp(is_waitp),
    .is_waite(is_waite),
    .is_waits(is_waits),
    .is_waitb(is_waitb),
    .is_dly(is_dly),
    .is_setd(is_setd),
    .is_nop(is_nop),
    .is_push(is_push),
    .is_pop(is_pop),
    .is_sho(is_sho),
    .is_shi(is_shi),
    .is_ldsr(is_ldsr),
    .is_stsr(is_stsr),
    .is_crci(is_crci),
    .is_stcrc(is_stcrc),
    .is_csrr(is_csrr),
    .is_csrw(is_csrw),
    .is_clr(is_clr),
    .is_sig(is_sig),
    .is_ld(is_ld),
    .is_st(is_st),
    .is_reserved(is_reserved)
);

`default_nettype wire
