/*
 * loom_isa_props: ISA-1 (docs/VERIFICATION.md L4).
 * GENERATED by formal/gen_isa_props.py from isa/isa.yaml (ISA version 0.4.0).
 * DO NOT EDIT.
 * SPDX-License-Identifier: Apache-2.0
 *
 * Formal only. Bound into loom_decode and loom_core; never read by synthesis
 * or by the TT flow.
 *
 * The mask/match table below is the one in isa/isa.yaml, read through
 * tools.loomisa. src/loom_decode.v is generated from the same YAML by a
 * different generator, so the properties compare two independent renderings
 * of the same source over all 2**16 words.
 *
 * 64 instructions, 49664 of 65536 words decode to one of them.
 */

`default_nettype none

/*
 * loom_isa_core_props: the other half of ISA-1, "reserved patterns
 * decode to NOP and set the bad opcode bit", which is a property of
 * loom_core and not of the decoder.
 *
 * SEMANTICS 9: "Any word that matches no instruction in isa.yaml, and
 * any instruction whose feature is not built, executes as NOP (one
 * slot, PC <= next) and commits BADOP[t] <= 1. BADOP is sticky until
 * the host clears it."
 *
 * Read through the retire record of SEMANTICS 8, which is valid during
 * the W cycle of every valid slot.
 */
module loom_isa_core_props (
    input wire        clk,
    input wire        rst_n,
    input wire        tr_valid,
    input wire [1:0]  tr_thread,
    input wire [9:0]  tr_pc,
    input wire [15:0] tr_ir,
    input wire        tr_done,
    input wire        tr_we,
    input wire [2:0]  tr_flags,
    input wire [9:0]  tr_next_pc,
    input wire        w_mem_done,   // the slot in W completes an LD/ST (6.11)
    input wire [15:0] badop,
    input wire        h_badop_clr_we,
    input wire [15:0] h_badop_clr
);

  reg f_past_valid = 1'b0;
  always @(posedge clk) f_past_valid <= 1'b1;
  always @(*) if (!f_past_valid) assume (!rst_n);

  wire [63:0] m;
  assign m[0  ] = (tr_ir & 16'hFE00) == 16'h0000;   // ADD
  assign m[1  ] = (tr_ir & 16'hFE00) == 16'h0200;   // SUB
  assign m[2  ] = (tr_ir & 16'hFE00) == 16'h0400;   // AND
  assign m[3  ] = (tr_ir & 16'hFE00) == 16'h0600;   // OR
  assign m[4  ] = (tr_ir & 16'hFE00) == 16'h0800;   // XOR
  assign m[5  ] = (tr_ir & 16'hFE00) == 16'h0A00;   // SHL
  assign m[6  ] = (tr_ir & 16'hFE00) == 16'h0C00;   // SHR
  assign m[7  ] = (tr_ir & 16'hFE00) == 16'h0E00;   // ROR
  assign m[8  ] = (tr_ir & 16'hFE00) == 16'h1000;   // ADDI
  assign m[9  ] = (tr_ir & 16'hFE00) == 16'h1200;   // SUBI
  assign m[10 ] = (tr_ir & 16'hFE00) == 16'h1400;   // ANDI
  assign m[11 ] = (tr_ir & 16'hFE00) == 16'h1600;   // ORI
  assign m[12 ] = (tr_ir & 16'hFE00) == 16'h1800;   // XORI
  assign m[13 ] = (tr_ir & 16'hFE00) == 16'h1A00;   // SHLI
  assign m[14 ] = (tr_ir & 16'hFE00) == 16'h1C00;   // SHRI
  assign m[15 ] = (tr_ir & 16'hFE00) == 16'h1E00;   // CMPI
  assign m[16 ] = (tr_ir & 16'hF800) == 16'h2000;   // LDI
  assign m[17 ] = (tr_ir & 16'hF800) == 16'h2800;   // LDIH
  assign m[18 ] = (tr_ir & 16'hFE00) == 16'h3000;   // MOV
  assign m[19 ] = (tr_ir & 16'hFE00) == 16'h3200;   // NOT
  assign m[20 ] = (tr_ir & 16'hFE00) == 16'h3400;   // NEG
  assign m[21 ] = (tr_ir & 16'hFE00) == 16'h3600;   // CMP
  assign m[22 ] = (tr_ir & 16'hFE00) == 16'h3800;   // TEST
  assign m[23 ] = (tr_ir & 16'hFE00) == 16'h3A00;   // REV
  assign m[24 ] = (tr_ir & 16'hFE00) == 16'h3C00;   // PAR
  assign m[25 ] = (tr_ir & 16'hFE00) == 16'h3E00;   // SWAP
  assign m[26 ] = (tr_ir & 16'hFC00) == 16'h4000;   // JMP
  assign m[27 ] = (tr_ir & 16'hFC00) == 16'h4400;   // CALL
  assign m[28 ] = (tr_ir & 16'hFC00) == 16'h4800;   // RET
  assign m[29 ] = (tr_ir & 16'hFC00) == 16'h4C00;   // HALT
  assign m[30 ] = (tr_ir & 16'hFF00) == 16'h5000;   // BZ
  assign m[31 ] = (tr_ir & 16'hFF00) == 16'h5200;   // BNZ
  assign m[32 ] = (tr_ir & 16'hFF00) == 16'h5400;   // BC
  assign m[33 ] = (tr_ir & 16'hFF00) == 16'h5600;   // BNC
  assign m[34 ] = (tr_ir & 16'hFF00) == 16'h5800;   // BT
  assign m[35 ] = (tr_ir & 16'hFF00) == 16'h5A00;   // BNT
  assign m[36 ] = (tr_ir & 16'hF800) == 16'h6000;   // DJNZ
  assign m[37 ] = (tr_ir & 16'hF000) == 16'h7000;   // JP
  assign m[38 ] = (tr_ir & 16'hFC00) == 16'h8000;   // SETP
  assign m[39 ] = (tr_ir & 16'hFC00) == 16'h8400;   // OEP
  assign m[40 ] = (tr_ir & 16'hFC00) == 16'h8800;   // OUT
  assign m[41 ] = (tr_ir & 16'hFC00) == 16'h8C00;   // IN
  assign m[42 ] = (tr_ir & 16'hFE00) == 16'h9000;   // WAITD
  assign m[43 ] = (tr_ir & 16'hFE00) == 16'h9200;   // WAITP
  assign m[44 ] = (tr_ir & 16'hFE00) == 16'h9400;   // WAITE
  assign m[45 ] = (tr_ir & 16'hFE00) == 16'h9600;   // WAITS
  assign m[46 ] = (tr_ir & 16'hFE00) == 16'h9800;   // WAITB
  assign m[47 ] = (tr_ir & 16'hFE00) == 16'h9A00;   // DLY
  assign m[48 ] = (tr_ir & 16'hFE00) == 16'h9C00;   // SETD
  assign m[49 ] = (tr_ir & 16'hFE00) == 16'h9E00;   // NOP
  assign m[50 ] = (tr_ir & 16'hFF80) == 16'hA000;   // PUSH
  assign m[51 ] = (tr_ir & 16'hFF80) == 16'hA080;   // POP
  assign m[52 ] = (tr_ir & 16'hFF80) == 16'hA400;   // SHO
  assign m[53 ] = (tr_ir & 16'hFF80) == 16'hA480;   // SHI
  assign m[54 ] = (tr_ir & 16'hFF80) == 16'hA800;   // LDSR
  assign m[55 ] = (tr_ir & 16'hFF80) == 16'hA880;   // STSR
  assign m[56 ] = (tr_ir & 16'hFF80) == 16'hAC00;   // CRCI
  assign m[57 ] = (tr_ir & 16'hFF80) == 16'hAC80;   // STCRC
  assign m[58 ] = (tr_ir & 16'hF800) == 16'hB000;   // CSRR
  assign m[59 ] = (tr_ir & 16'hF800) == 16'hB800;   // CSRW
  assign m[60 ] = (tr_ir & 16'hF800) == 16'hC000;   // CLR
  assign m[61 ] = (tr_ir & 16'hF800) == 16'hC800;   // SIG
  assign m[62 ] = (tr_ir & 16'hF800) == 16'hD000;   // LD
  assign m[63 ] = (tr_ir & 16'hF800) == 16'hD800;   // ST
  // SEMANTICS 6.11: the completion slot of an LD/ST decodes nothing; the
  // word it carries is data, so a reserved-looking one is not a reserved
  // instruction. Before slice B every valid slot decoded its word.
  wire f_reserved = (m == 64'd0) && !w_mem_done;

  wire [9:0] f_next = tr_pc + 10'd1;      // SEMANTICS 6: next = (PC + 1) mod 2^10

  reg        p_valid, p_reserved;
  reg [1:0]  p_thread;
  reg [2:0]  p_flags;
  reg        p_rst_n;
  always @(posedge clk) begin
    p_valid    <= tr_valid;
    p_reserved <= f_reserved;
    p_thread   <= tr_thread;
    p_flags    <= tr_flags;
    p_rst_n    <= rst_n;
  end

  // ================================================================
  // ISA-2A: a reserved word retires as a NOP: one slot (`done`), no
  // register write, PC <= next.
  // ================================================================
  always @(*) if (f_past_valid && rst_n && tr_valid && f_reserved) begin
    assert (tr_done);
    assert (!tr_we);
    assert (tr_next_pc == f_next);
  end

  // ================================================================
  // ISA-2C: it sets the thread's bad opcode bit at its commit edge,
  // and BADOP is sticky until the host clears it.
  // ================================================================
  reg [3:0] p_badop;
  always @(posedge clk) p_badop <= badop[3:0];
  always @(posedge clk)
    if (f_past_valid && p_rst_n && p_valid && p_reserved)
      assert (badop[p_thread]);

  genvar t;
  generate
    for (t = 0; t < 4; t = t + 1) begin : g_sticky
      reg p_clr;
      always @(posedge clk) p_clr <= h_badop_clr_we & h_badop_clr[t];
      always @(posedge clk)
        if (f_past_valid && p_rst_n && p_badop[t] && !p_clr)
          assert (badop[t]);
    end
  endgenerate

  // ---------------------------------------- cover (anti-vacuity)
  always @(posedge clk) if (f_past_valid && p_rst_n) begin
    cover (tr_valid && f_reserved);        // a reserved word retires
    cover (tr_valid && !f_reserved && !w_mem_done);  // a real instruction retires
    cover (tr_valid && w_mem_done && m == 64'd0);  // an LD/ST completes on a reserved-looking data word
    cover (badop[3:0] != 4'd0);            // BADOP can be set
    cover (p_badop != 4'd0 && badop[3:0] == 4'd0);  // and cleared
  end

endmodule

bind loom_core loom_isa_core_props u_isa_core_props (
    .clk(clk), .rst_n(rst_n),
    .tr_valid(tr_valid), .tr_thread(tr_thread), .tr_pc(tr_pc),
    .tr_ir(tr_ir), .tr_done(tr_done), .tr_we(tr_we),
    .tr_flags(tr_flags), .tr_next_pc(tr_next_pc),
    .w_mem_done(w_mem_done),
    .badop(badop),
    .h_badop_clr_we(h_badop_clr_we), .h_badop_clr(h_badop_clr)
);

`default_nettype wire
