#!/usr/bin/env python3
"""Generate formal/props/loom_isa_props.v from isa/isa.yaml.

ISA-1 (docs/VERIFICATION.md L4): "every 16-bit pattern decodes to exactly one
instruction class (generated from isa.yaml); reserved patterns decode to NOP
and set the bad opcode bit."

The decode table in the generated file comes from `tools.loomisa`, the only
code allowed to parse isa/isa.yaml (repo CLAUDE.md). It is written
independently of src/loom_decode.v, which is generated from the same YAML by
a different generator: the proof is that the two agree for all 2**16 words.

Run from the repo root, inside the dev shell:

    "$LOOM_PY" formal/gen_isa_props.py

scripts/formal.sh regenerates it and fails if the checked-in file differs, the
same rule the repo applies to every other generated file.
"""

import pathlib
import sys

ROOT = pathlib.Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT))

from tools import loomisa                                    # noqa: E402

OUT = ROOT / "formal" / "props" / "loom_isa_props.v"
OUT_CORE = ROOT / "formal" / "props" / "loom_isa_core_props.v"

HEADER = """\
/*
 * loom_isa_props: ISA-1 (docs/VERIFICATION.md L4).
 * GENERATED by formal/gen_isa_props.py from isa/isa.yaml (ISA version {ver}).
 * DO NOT EDIT.
 * SPDX-License-Identifier: Apache-2.0
 *
 * Formal only. Bound into loom_decode and loom_core; never read by synthesis
 * or by the TT flow.
 *
 * The mask/match table below is the one in isa/isa.yaml, read through
 * tools.loomisa. src/loom_decode.v is generated from the same YAML by a
 * different generator, so the properties compare two independent renderings
 * of the same source over all 2**16 words.
 *
 * {n} instructions, {used} of 65536 words decode to one of them.
 */

`default_nettype none
"""


def emit_decode_props(isa):
    ins = isa.instructions
    n = len(ins)
    ports = ",\n".join("    input wire        is_%s" % i.name.lower() for i in ins)
    lines = []
    lines.append("module loom_isa_props (")
    lines.append("    input wire [15:0] ir,")
    lines.append(ports + ",")
    lines.append("    input wire        is_reserved")
    lines.append(");")
    lines.append("")
    lines.append("  // One bit per instruction of isa/isa.yaml: the word matches its")
    lines.append("  // encoding. Straight from the YAML, not from the decoder.")
    lines.append("  wire [%d:0] m;" % (n - 1))
    for k, i in enumerate(ins):
        lines.append("  assign m[%-3d] = (ir & 16'h%04X) == 16'h%04X;   // %s"
                     % (k, i.mask, i.match, i.name))
    lines.append("")
    lines.append("  // ================================================================")
    lines.append("  // ISA-1A: every 16-bit pattern matches at most one instruction, so")
    lines.append("  // \"decodes to exactly one instruction class\" holds for every word")
    lines.append("  // that decodes at all. ($onehot0 written out, for portability.)")
    lines.append("  // ================================================================")
    lines.append("  always @(*) assert ((m & (m - %d'd1)) == %d'd0);" % (n, n))
    lines.append("")
    lines.append("  // ================================================================")
    lines.append("  // ISA-1B: the decoder's one-hot strobes are exactly those matches.")
    lines.append("  // ================================================================")
    lines.append("  always @(*) begin")
    for k, i in enumerate(ins):
        lines.append("    assert (is_%-7s == m[%d]);" % (i.name.lower(), k))
    lines.append("  end")
    lines.append("")
    lines.append("  // ================================================================")
    lines.append("  // ISA-1C: `is_reserved` is exactly \"no instruction matches\"")
    lines.append("  // (SEMANTICS 9: \"Any word that matches no instruction in isa.yaml")
    lines.append("  // ... executes as NOP ... and commits BADOP[t] <= 1\").")
    lines.append("  // ================================================================")
    lines.append("  always @(*) assert (is_reserved == (m == %d'd0));" % n)
    lines.append("")
    lines.append("  // ---------------------------------------- cover (anti-vacuity)")
    lines.append("  always @(*) begin")
    lines.append("    cover (is_reserved);")
    lines.append("    cover (m != %d'd0);" % n)
    for k, i in enumerate(ins):
        lines.append("    cover (m[%d]);" % k)
    lines.append("  end")
    lines.append("")
    lines.append("endmodule")
    lines.append("")
    lines.append("bind loom_decode loom_isa_props u_isa_props (")
    lines.append("    .ir(ir),")
    for i in ins:
        lines.append("    .is_%s(is_%s)," % (i.name.lower(), i.name.lower()))
    lines.append("    .is_reserved(is_reserved)")
    lines.append(");")
    return "\n".join(lines)


def emit_core_props(isa):
    ins = isa.instructions
    n = len(ins)
    lines = []
    lines.append("")
    lines.append("/*")
    lines.append(" * loom_isa_core_props: the other half of ISA-1, \"reserved patterns")
    lines.append(" * decode to NOP and set the bad opcode bit\", which is a property of")
    lines.append(" * loom_core and not of the decoder.")
    lines.append(" *")
    lines.append(" * SEMANTICS 9: \"Any word that matches no instruction in isa.yaml, and")
    lines.append(" * any instruction whose feature is not built, executes as NOP (one")
    lines.append(" * slot, PC <= next) and commits BADOP[t] <= 1. BADOP is sticky until")
    lines.append(" * the host clears it.\"")
    lines.append(" *")
    lines.append(" * Read through the retire record of SEMANTICS 8, which is valid during")
    lines.append(" * the W cycle of every valid slot.")
    lines.append(" */")
    lines.append("module loom_isa_core_props (")
    lines.append("    input wire        clk,")
    lines.append("    input wire        rst_n,")
    lines.append("    input wire        tr_valid,")
    lines.append("    input wire [1:0]  tr_thread,")
    lines.append("    input wire [9:0]  tr_pc,")
    lines.append("    input wire [15:0] tr_ir,")
    lines.append("    input wire        tr_done,")
    lines.append("    input wire        tr_we,")
    lines.append("    input wire [2:0]  tr_flags,")
    lines.append("    input wire [9:0]  tr_next_pc,")
    lines.append("    input wire        w_mem_done,   // the slot in W completes an LD/ST (6.11)")
    lines.append("    input wire [15:0] badop,")
    lines.append("    input wire        h_badop_clr_we,")
    lines.append("    input wire [15:0] h_badop_clr")
    lines.append(");")
    lines.append("")
    lines.append("  reg f_past_valid = 1'b0;")
    lines.append("  always @(posedge clk) f_past_valid <= 1'b1;")
    lines.append("  always @(*) if (!f_past_valid) assume (!rst_n);")
    lines.append("")
    lines.append("  wire [%d:0] m;" % (n - 1))
    for k, i in enumerate(ins):
        lines.append("  assign m[%-3d] = (tr_ir & 16'h%04X) == 16'h%04X;   // %s"
                     % (k, i.mask, i.match, i.name))
    lines.append("  // SEMANTICS 6.11: the completion slot of an LD/ST decodes nothing; the")
    lines.append("  // word it carries is data, so a reserved-looking one is not a reserved")
    lines.append("  // instruction. Before slice B every valid slot decoded its word.")
    lines.append("  wire f_reserved = (m == %d'd0) && !w_mem_done;" % n)
    lines.append("")
    lines.append("  wire [9:0] f_next = tr_pc + 10'd1;      // SEMANTICS 6: next = (PC + 1) mod 2^10")
    lines.append("")
    lines.append("  reg        p_valid, p_reserved;")
    lines.append("  reg [1:0]  p_thread;")
    lines.append("  reg [2:0]  p_flags;")
    lines.append("  reg        p_rst_n;")
    lines.append("  always @(posedge clk) begin")
    lines.append("    p_valid    <= tr_valid;")
    lines.append("    p_reserved <= f_reserved;")
    lines.append("    p_thread   <= tr_thread;")
    lines.append("    p_flags    <= tr_flags;")
    lines.append("    p_rst_n    <= rst_n;")
    lines.append("  end")
    lines.append("")
    lines.append("  // ================================================================")
    lines.append("  // ISA-2A: a reserved word retires as a NOP: one slot (`done`), no")
    lines.append("  // register write, PC <= next.")
    lines.append("  // ================================================================")
    lines.append("  always @(*) if (f_past_valid && rst_n && tr_valid && f_reserved) begin")
    lines.append("    assert (tr_done);")
    lines.append("    assert (!tr_we);")
    lines.append("    assert (tr_next_pc == f_next);")
    lines.append("  end")
    lines.append("")
    lines.append("  // ================================================================")
    lines.append("  // ISA-2C: it sets the thread's bad opcode bit at its commit edge,")
    lines.append("  // and BADOP is sticky until the host clears it.")
    lines.append("  // ================================================================")
    lines.append("  reg [3:0] p_badop;")
    lines.append("  always @(posedge clk) p_badop <= badop[3:0];")
    lines.append("  always @(posedge clk)")
    lines.append("    if (f_past_valid && p_rst_n && p_valid && p_reserved)")
    lines.append("      assert (badop[p_thread]);")
    lines.append("")
    lines.append("  genvar t;")
    lines.append("  generate")
    lines.append("    for (t = 0; t < 4; t = t + 1) begin : g_sticky")
    lines.append("      reg p_clr;")
    lines.append("      always @(posedge clk) p_clr <= h_badop_clr_we & h_badop_clr[t];")
    lines.append("      always @(posedge clk)")
    lines.append("        if (f_past_valid && p_rst_n && p_badop[t] && !p_clr)")
    lines.append("          assert (badop[t]);")
    lines.append("    end")
    lines.append("  endgenerate")
    lines.append("")
    lines.append("  // ---------------------------------------- cover (anti-vacuity)")
    lines.append("  always @(posedge clk) if (f_past_valid && p_rst_n) begin")
    lines.append("    cover (tr_valid && f_reserved);        // a reserved word retires")
    lines.append("    cover (tr_valid && !f_reserved && !w_mem_done);  // a real instruction retires")
    lines.append("    cover (tr_valid && w_mem_done && m == %d'd0);  // an LD/ST completes on a reserved-looking data word" % n)
    lines.append("    cover (badop[3:0] != 4'd0);            // BADOP can be set")
    lines.append("    cover (p_badop != 4'd0 && badop[3:0] == 4'd0);  // and cleared")
    lines.append("  end")
    lines.append("")
    lines.append("endmodule")
    lines.append("")
    lines.append("bind loom_core loom_isa_core_props u_isa_core_props (")
    lines.append("    .clk(clk), .rst_n(rst_n),")
    lines.append("    .tr_valid(tr_valid), .tr_thread(tr_thread), .tr_pc(tr_pc),")
    lines.append("    .tr_ir(tr_ir), .tr_done(tr_done), .tr_we(tr_we),")
    lines.append("    .tr_flags(tr_flags), .tr_next_pc(tr_next_pc),")
    lines.append("    .w_mem_done(w_mem_done),")
    lines.append("    .badop(badop),")
    lines.append("    .h_badop_clr_we(h_badop_clr_we), .h_badop_clr(h_badop_clr)")
    lines.append(");")
    lines.append("")
    lines.append("`default_nettype wire")
    return "\n".join(lines)


def main(argv):
    isa = loomisa.load()
    used, total = isa.coverage()
    header = HEADER.format(ver=isa.version, n=len(isa.instructions), used=used)
    files = {
        OUT:      header + emit_decode_props(isa) + "\n\n`default_nettype wire\n",
        OUT_CORE: header + emit_core_props(isa) + "\n",
    }

    if "--check" in argv:
        stale = [p for p, text in files.items()
                 if (p.read_text(encoding="utf-8") if p.exists() else "") != text]
        if stale:
            print("stale, run \"$LOOM_PY\" formal/gen_isa_props.py: "
                  + ", ".join(p.name for p in stale), file=sys.stderr)
            return 1
        print("formal ISA properties up to date (%d instructions)"
              % len(isa.instructions))
        return 0

    for p, text in files.items():
        p.write_text(text, encoding="utf-8")
        print("wrote %s" % p)
    print("%d instructions, %d/%d words decode to one of them"
          % (len(isa.instructions), used, total))
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
