// GENERATED by tools/loomisa from isa/isa.yaml. DO NOT EDIT.
// ISA version 0.2.0. Include inside a module body.
// Decode with: (ir & ISA_<NAME>_MASK) == ISA_<NAME>_MATCH
/* verilator lint_off UNUSEDPARAM */

localparam integer ISA_THREADS  = 4;
localparam integer ISA_PC_BITS  = 10;
localparam integer ISA_REG_BITS = 16;

// ADD: 0000fffdddaaabbb  (one_slot)
localparam [15:0] ISA_ADD_MASK  = 16'hFE00;
localparam [15:0] ISA_ADD_MATCH = 16'h0000;
localparam integer ISA_ADD_RD_HI = 8;
localparam integer ISA_ADD_RD_LO = 6;
localparam integer ISA_ADD_RA_HI = 5;
localparam integer ISA_ADD_RA_LO = 3;
localparam integer ISA_ADD_RB_HI = 2;
localparam integer ISA_ADD_RB_LO = 0;

// SUB: 0000fffdddaaabbb  (one_slot)
localparam [15:0] ISA_SUB_MASK  = 16'hFE00;
localparam [15:0] ISA_SUB_MATCH = 16'h0200;
localparam integer ISA_SUB_RD_HI = 8;
localparam integer ISA_SUB_RD_LO = 6;
localparam integer ISA_SUB_RA_HI = 5;
localparam integer ISA_SUB_RA_LO = 3;
localparam integer ISA_SUB_RB_HI = 2;
localparam integer ISA_SUB_RB_LO = 0;

// AND: 0000fffdddaaabbb  (one_slot)
localparam [15:0] ISA_AND_MASK  = 16'hFE00;
localparam [15:0] ISA_AND_MATCH = 16'h0400;
localparam integer ISA_AND_RD_HI = 8;
localparam integer ISA_AND_RD_LO = 6;
localparam integer ISA_AND_RA_HI = 5;
localparam integer ISA_AND_RA_LO = 3;
localparam integer ISA_AND_RB_HI = 2;
localparam integer ISA_AND_RB_LO = 0;

// OR: 0000fffdddaaabbb  (one_slot)
localparam [15:0] ISA_OR_MASK  = 16'hFE00;
localparam [15:0] ISA_OR_MATCH = 16'h0600;
localparam integer ISA_OR_RD_HI = 8;
localparam integer ISA_OR_RD_LO = 6;
localparam integer ISA_OR_RA_HI = 5;
localparam integer ISA_OR_RA_LO = 3;
localparam integer ISA_OR_RB_HI = 2;
localparam integer ISA_OR_RB_LO = 0;

// XOR: 0000fffdddaaabbb  (one_slot)
localparam [15:0] ISA_XOR_MASK  = 16'hFE00;
localparam [15:0] ISA_XOR_MATCH = 16'h0800;
localparam integer ISA_XOR_RD_HI = 8;
localparam integer ISA_XOR_RD_LO = 6;
localparam integer ISA_XOR_RA_HI = 5;
localparam integer ISA_XOR_RA_LO = 3;
localparam integer ISA_XOR_RB_HI = 2;
localparam integer ISA_XOR_RB_LO = 0;

// SHL: 0000fffdddaaabbb  (one_slot)
localparam [15:0] ISA_SHL_MASK  = 16'hFE00;
localparam [15:0] ISA_SHL_MATCH = 16'h0A00;
localparam integer ISA_SHL_RD_HI = 8;
localparam integer ISA_SHL_RD_LO = 6;
localparam integer ISA_SHL_RA_HI = 5;
localparam integer ISA_SHL_RA_LO = 3;
localparam integer ISA_SHL_RB_HI = 2;
localparam integer ISA_SHL_RB_LO = 0;

// SHR: 0000fffdddaaabbb  (one_slot)
localparam [15:0] ISA_SHR_MASK  = 16'hFE00;
localparam [15:0] ISA_SHR_MATCH = 16'h0C00;
localparam integer ISA_SHR_RD_HI = 8;
localparam integer ISA_SHR_RD_LO = 6;
localparam integer ISA_SHR_RA_HI = 5;
localparam integer ISA_SHR_RA_LO = 3;
localparam integer ISA_SHR_RB_HI = 2;
localparam integer ISA_SHR_RB_LO = 0;

// ROR: 0000fffdddaaabbb  (one_slot)
localparam [15:0] ISA_ROR_MASK  = 16'hFE00;
localparam [15:0] ISA_ROR_MATCH = 16'h0E00;
localparam integer ISA_ROR_RD_HI = 8;
localparam integer ISA_ROR_RD_LO = 6;
localparam integer ISA_ROR_RA_HI = 5;
localparam integer ISA_ROR_RA_LO = 3;
localparam integer ISA_ROR_RB_HI = 2;
localparam integer ISA_ROR_RB_LO = 0;

// ADDI: 0001fffdddiiiiii  (one_slot)
localparam [15:0] ISA_ADDI_MASK  = 16'hFE00;
localparam [15:0] ISA_ADDI_MATCH = 16'h1000;
localparam integer ISA_ADDI_RD_HI = 8;
localparam integer ISA_ADDI_RD_LO = 6;
localparam integer ISA_ADDI_IMM_HI = 5;
localparam integer ISA_ADDI_IMM_LO = 0;

// SUBI: 0001fffdddiiiiii  (one_slot)
localparam [15:0] ISA_SUBI_MASK  = 16'hFE00;
localparam [15:0] ISA_SUBI_MATCH = 16'h1200;
localparam integer ISA_SUBI_RD_HI = 8;
localparam integer ISA_SUBI_RD_LO = 6;
localparam integer ISA_SUBI_IMM_HI = 5;
localparam integer ISA_SUBI_IMM_LO = 0;

// ANDI: 0001fffdddiiiiii  (one_slot)
localparam [15:0] ISA_ANDI_MASK  = 16'hFE00;
localparam [15:0] ISA_ANDI_MATCH = 16'h1400;
localparam integer ISA_ANDI_RD_HI = 8;
localparam integer ISA_ANDI_RD_LO = 6;
localparam integer ISA_ANDI_IMM_HI = 5;
localparam integer ISA_ANDI_IMM_LO = 0;

// ORI: 0001fffdddiiiiii  (one_slot)
localparam [15:0] ISA_ORI_MASK  = 16'hFE00;
localparam [15:0] ISA_ORI_MATCH = 16'h1600;
localparam integer ISA_ORI_RD_HI = 8;
localparam integer ISA_ORI_RD_LO = 6;
localparam integer ISA_ORI_IMM_HI = 5;
localparam integer ISA_ORI_IMM_LO = 0;

// XORI: 0001fffdddiiiiii  (one_slot)
localparam [15:0] ISA_XORI_MASK  = 16'hFE00;
localparam [15:0] ISA_XORI_MATCH = 16'h1800;
localparam integer ISA_XORI_RD_HI = 8;
localparam integer ISA_XORI_RD_LO = 6;
localparam integer ISA_XORI_IMM_HI = 5;
localparam integer ISA_XORI_IMM_LO = 0;

// SHLI: 0001fffdddiiiiii  (one_slot)
localparam [15:0] ISA_SHLI_MASK  = 16'hFE00;
localparam [15:0] ISA_SHLI_MATCH = 16'h1A00;
localparam integer ISA_SHLI_RD_HI = 8;
localparam integer ISA_SHLI_RD_LO = 6;
localparam integer ISA_SHLI_IMM_HI = 5;
localparam integer ISA_SHLI_IMM_LO = 0;

// SHRI: 0001fffdddiiiiii  (one_slot)
localparam [15:0] ISA_SHRI_MASK  = 16'hFE00;
localparam [15:0] ISA_SHRI_MATCH = 16'h1C00;
localparam integer ISA_SHRI_RD_HI = 8;
localparam integer ISA_SHRI_RD_LO = 6;
localparam integer ISA_SHRI_IMM_HI = 5;
localparam integer ISA_SHRI_IMM_LO = 0;

// CMPI: 0001fffdddiiiiii  (one_slot)
localparam [15:0] ISA_CMPI_MASK  = 16'hFE00;
localparam [15:0] ISA_CMPI_MATCH = 16'h1E00;
localparam integer ISA_CMPI_RD_HI = 8;
localparam integer ISA_CMPI_RD_LO = 6;
localparam integer ISA_CMPI_IMM_HI = 5;
localparam integer ISA_CMPI_IMM_LO = 0;

// LDI: 00100dddiiiiiiii  (one_slot)
localparam [15:0] ISA_LDI_MASK  = 16'hF800;
localparam [15:0] ISA_LDI_MATCH = 16'h2000;
localparam integer ISA_LDI_RD_HI = 10;
localparam integer ISA_LDI_RD_LO = 8;
localparam integer ISA_LDI_IMM_HI = 7;
localparam integer ISA_LDI_IMM_LO = 0;

// LDIH: 00101dddiiiiiiii  (one_slot)
localparam [15:0] ISA_LDIH_MASK  = 16'hF800;
localparam [15:0] ISA_LDIH_MATCH = 16'h2800;
localparam integer ISA_LDIH_RD_HI = 10;
localparam integer ISA_LDIH_RD_LO = 8;
localparam integer ISA_LDIH_IMM_HI = 7;
localparam integer ISA_LDIH_IMM_LO = 0;

// MOV: 0011fffdddaaa---  (one_slot)
localparam [15:0] ISA_MOV_MASK  = 16'hFE00;
localparam [15:0] ISA_MOV_MATCH = 16'h3000;
localparam integer ISA_MOV_RD_HI = 8;
localparam integer ISA_MOV_RD_LO = 6;
localparam integer ISA_MOV_RA_HI = 5;
localparam integer ISA_MOV_RA_LO = 3;

// NOT: 0011fffdddaaa---  (one_slot)
localparam [15:0] ISA_NOT_MASK  = 16'hFE00;
localparam [15:0] ISA_NOT_MATCH = 16'h3200;
localparam integer ISA_NOT_RD_HI = 8;
localparam integer ISA_NOT_RD_LO = 6;
localparam integer ISA_NOT_RA_HI = 5;
localparam integer ISA_NOT_RA_LO = 3;

// NEG: 0011fffdddaaa---  (one_slot)
localparam [15:0] ISA_NEG_MASK  = 16'hFE00;
localparam [15:0] ISA_NEG_MATCH = 16'h3400;
localparam integer ISA_NEG_RD_HI = 8;
localparam integer ISA_NEG_RD_LO = 6;
localparam integer ISA_NEG_RA_HI = 5;
localparam integer ISA_NEG_RA_LO = 3;

// CMP: 0011fffdddaaa---  (one_slot)
localparam [15:0] ISA_CMP_MASK  = 16'hFE00;
localparam [15:0] ISA_CMP_MATCH = 16'h3600;
localparam integer ISA_CMP_RD_HI = 8;
localparam integer ISA_CMP_RD_LO = 6;
localparam integer ISA_CMP_RA_HI = 5;
localparam integer ISA_CMP_RA_LO = 3;

// TEST: 0011fffdddaaa---  (one_slot)
localparam [15:0] ISA_TEST_MASK  = 16'hFE00;
localparam [15:0] ISA_TEST_MATCH = 16'h3800;
localparam integer ISA_TEST_RD_HI = 8;
localparam integer ISA_TEST_RD_LO = 6;
localparam integer ISA_TEST_RA_HI = 5;
localparam integer ISA_TEST_RA_LO = 3;

// REV: 0011fffdddaaa---  (one_slot)
localparam [15:0] ISA_REV_MASK  = 16'hFE00;
localparam [15:0] ISA_REV_MATCH = 16'h3A00;
localparam integer ISA_REV_RD_HI = 8;
localparam integer ISA_REV_RD_LO = 6;
localparam integer ISA_REV_RA_HI = 5;
localparam integer ISA_REV_RA_LO = 3;

// PAR: 0011fffdddaaa---  (one_slot)
localparam [15:0] ISA_PAR_MASK  = 16'hFE00;
localparam [15:0] ISA_PAR_MATCH = 16'h3C00;
localparam integer ISA_PAR_RD_HI = 8;
localparam integer ISA_PAR_RD_LO = 6;
localparam integer ISA_PAR_RA_HI = 5;
localparam integer ISA_PAR_RA_LO = 3;

// SWAP: 0011fffdddaaa---  (one_slot)
localparam [15:0] ISA_SWAP_MASK  = 16'hFE00;
localparam [15:0] ISA_SWAP_MATCH = 16'h3E00;
localparam integer ISA_SWAP_RD_HI = 8;
localparam integer ISA_SWAP_RD_LO = 6;
localparam integer ISA_SWAP_RA_HI = 5;
localparam integer ISA_SWAP_RA_LO = 3;

// JMP: 010000AAAAAAAAAA  (one_slot)
localparam [15:0] ISA_JMP_MASK  = 16'hFC00;
localparam [15:0] ISA_JMP_MATCH = 16'h4000;
localparam integer ISA_JMP_ABS_HI = 9;
localparam integer ISA_JMP_ABS_LO = 0;

// CALL: 010001AAAAAAAAAA  (one_slot)
localparam [15:0] ISA_CALL_MASK  = 16'hFC00;
localparam [15:0] ISA_CALL_MATCH = 16'h4400;
localparam integer ISA_CALL_ABS_HI = 9;
localparam integer ISA_CALL_ABS_LO = 0;

// RET: 010010----------  (one_slot)
localparam [15:0] ISA_RET_MASK  = 16'hFC00;
localparam [15:0] ISA_RET_MATCH = 16'h4800;

// HALT: 010011----------  (one_slot)
localparam [15:0] ISA_HALT_MASK  = 16'hFC00;
localparam [15:0] ISA_HALT_MATCH = 16'h4C00;

// BZ: 0101ccc0rrrrrrrr  (one_slot)
localparam [15:0] ISA_BZ_MASK  = 16'hFF00;
localparam [15:0] ISA_BZ_MATCH = 16'h5000;
localparam integer ISA_BZ_REL_HI = 7;
localparam integer ISA_BZ_REL_LO = 0;

// BNZ: 0101ccc0rrrrrrrr  (one_slot)
localparam [15:0] ISA_BNZ_MASK  = 16'hFF00;
localparam [15:0] ISA_BNZ_MATCH = 16'h5200;
localparam integer ISA_BNZ_REL_HI = 7;
localparam integer ISA_BNZ_REL_LO = 0;

// BC: 0101ccc0rrrrrrrr  (one_slot)
localparam [15:0] ISA_BC_MASK  = 16'hFF00;
localparam [15:0] ISA_BC_MATCH = 16'h5400;
localparam integer ISA_BC_REL_HI = 7;
localparam integer ISA_BC_REL_LO = 0;

// BNC: 0101ccc0rrrrrrrr  (one_slot)
localparam [15:0] ISA_BNC_MASK  = 16'hFF00;
localparam [15:0] ISA_BNC_MATCH = 16'h5600;
localparam integer ISA_BNC_REL_HI = 7;
localparam integer ISA_BNC_REL_LO = 0;

// BT: 0101ccc0rrrrrrrr  (one_slot)
localparam [15:0] ISA_BT_MASK  = 16'hFF00;
localparam [15:0] ISA_BT_MATCH = 16'h5800;
localparam integer ISA_BT_REL_HI = 7;
localparam integer ISA_BT_REL_LO = 0;

// BNT: 0101ccc0rrrrrrrr  (one_slot)
localparam [15:0] ISA_BNT_MASK  = 16'hFF00;
localparam [15:0] ISA_BNT_MATCH = 16'h5A00;
localparam integer ISA_BNT_REL_HI = 7;
localparam integer ISA_BNT_REL_LO = 0;

// DJNZ: 01100dddrrrrrrrr  (one_slot)
localparam [15:0] ISA_DJNZ_MASK  = 16'hF800;
localparam [15:0] ISA_DJNZ_MATCH = 16'h6000;
localparam integer ISA_DJNZ_RD_HI = 10;
localparam integer ISA_DJNZ_RD_LO = 8;
localparam integer ISA_DJNZ_REL_HI = 7;
localparam integer ISA_DJNZ_REL_LO = 0;

// JP: 0111vppppprrrrrr  (one_slot)
localparam [15:0] ISA_JP_MASK  = 16'hF000;
localparam [15:0] ISA_JP_MATCH = 16'h7000;
localparam integer ISA_JP_PIN_HI = 10;
localparam integer ISA_JP_PIN_LO = 6;
localparam integer ISA_JP_VAL_HI = 11;
localparam integer ISA_JP_VAL_LO = 11;
localparam integer ISA_JP_REL_HI = 5;
localparam integer ISA_JP_REL_LO = 0;

// SETP: 100000vppppp----  (one_slot)
localparam [15:0] ISA_SETP_MASK  = 16'hFC00;
localparam [15:0] ISA_SETP_MATCH = 16'h8000;
localparam integer ISA_SETP_PIN_HI = 8;
localparam integer ISA_SETP_PIN_LO = 4;
localparam integer ISA_SETP_VAL_HI = 9;
localparam integer ISA_SETP_VAL_LO = 9;

// OEP: 100001vppppp----  (one_slot)
localparam [15:0] ISA_OEP_MASK  = 16'hFC00;
localparam [15:0] ISA_OEP_MATCH = 16'h8400;
localparam integer ISA_OEP_PIN_HI = 8;
localparam integer ISA_OEP_PIN_LO = 4;
localparam integer ISA_OEP_VAL_HI = 9;
localparam integer ISA_OEP_VAL_LO = 9;

// OUT: 100010---aaa----  (one_slot)
localparam [15:0] ISA_OUT_MASK  = 16'hFC00;
localparam [15:0] ISA_OUT_MATCH = 16'h8800;
localparam integer ISA_OUT_RA_HI = 6;
localparam integer ISA_OUT_RA_LO = 4;

// IN: 100011---ddd----  (one_slot)
localparam [15:0] ISA_IN_MASK  = 16'hFC00;
localparam [15:0] ISA_IN_MATCH = 16'h8C00;
localparam integer ISA_IN_RD_HI = 6;
localparam integer ISA_IN_RD_LO = 4;

// WAITD: 1001000-iiiiiiii  (wait)
localparam [15:0] ISA_WAITD_MASK  = 16'hFE00;
localparam [15:0] ISA_WAITD_MATCH = 16'h9000;
localparam integer ISA_WAITD_IMM_HI = 7;
localparam integer ISA_WAITD_IMM_LO = 0;

// WAITP: 1001001vpppppT--  (wait)
localparam [15:0] ISA_WAITP_MASK  = 16'hFE00;
localparam [15:0] ISA_WAITP_MATCH = 16'h9200;
localparam integer ISA_WAITP_PIN_HI = 7;
localparam integer ISA_WAITP_PIN_LO = 3;
localparam integer ISA_WAITP_VAL_HI = 8;
localparam integer ISA_WAITP_VAL_LO = 8;
localparam integer ISA_WAITP_TMO_HI = 2;
localparam integer ISA_WAITP_TMO_LO = 2;

// WAITE: 1001010eepppppT-  (wait)
localparam [15:0] ISA_WAITE_MASK  = 16'hFE00;
localparam [15:0] ISA_WAITE_MATCH = 16'h9400;
localparam integer ISA_WAITE_PIN_HI = 6;
localparam integer ISA_WAITE_PIN_LO = 2;
localparam integer ISA_WAITE_EDGE_HI = 8;
localparam integer ISA_WAITE_EDGE_LO = 7;
localparam integer ISA_WAITE_TMO_HI = 1;
localparam integer ISA_WAITE_TMO_LO = 1;

// WAITS: 1001011nnnT-----  (wait)
localparam [15:0] ISA_WAITS_MASK  = 16'hFE00;
localparam [15:0] ISA_WAITS_MATCH = 16'h9600;
localparam integer ISA_WAITS_FLAG_HI = 8;
localparam integer ISA_WAITS_FLAG_LO = 6;
localparam integer ISA_WAITS_TMO_HI = 5;
localparam integer ISA_WAITS_TMO_LO = 5;

// WAITB: 1001100ccT------  (wait)
localparam [15:0] ISA_WAITB_MASK  = 16'hFE00;
localparam [15:0] ISA_WAITB_MATCH = 16'h9800;
localparam integer ISA_WAITB_COND_HI = 8;
localparam integer ISA_WAITB_COND_LO = 7;
localparam integer ISA_WAITB_TMO_HI = 6;
localparam integer ISA_WAITB_TMO_LO = 6;

// DLY: 1001101-iiiiiiii  (wait)
localparam [15:0] ISA_DLY_MASK  = 16'hFE00;
localparam [15:0] ISA_DLY_MATCH = 16'h9A00;
localparam integer ISA_DLY_IMM_HI = 7;
localparam integer ISA_DLY_IMM_LO = 0;

// SETD: 1001110-iiiiiiii  (one_slot)
localparam [15:0] ISA_SETD_MASK  = 16'hFE00;
localparam [15:0] ISA_SETD_MATCH = 16'h9C00;
localparam integer ISA_SETD_IMM_HI = 7;
localparam integer ISA_SETD_IMM_LO = 0;

// NOP: 1001111---------  (one_slot)
localparam [15:0] ISA_NOP_MASK  = 16'hFE00;
localparam [15:0] ISA_NOP_MATCH = 16'h9E00;

// PUSH: 101000000aaa----  (blocking)
localparam [15:0] ISA_PUSH_MASK  = 16'hFF80;
localparam [15:0] ISA_PUSH_MATCH = 16'hA000;
localparam integer ISA_PUSH_RA_HI = 6;
localparam integer ISA_PUSH_RA_LO = 4;

// POP: 101000001ddd----  (blocking)
localparam [15:0] ISA_POP_MASK  = 16'hFF80;
localparam [15:0] ISA_POP_MATCH = 16'hA080;
localparam integer ISA_POP_RD_HI = 6;
localparam integer ISA_POP_RD_LO = 4;

// SHO: 101001000-------  (one_slot)
localparam [15:0] ISA_SHO_MASK  = 16'hFF80;
localparam [15:0] ISA_SHO_MATCH = 16'hA400;

// SHI: 101001001-------  (one_slot)
localparam [15:0] ISA_SHI_MASK  = 16'hFF80;
localparam [15:0] ISA_SHI_MATCH = 16'hA480;

// LDSR: 101010000aaa----  (one_slot)
localparam [15:0] ISA_LDSR_MASK  = 16'hFF80;
localparam [15:0] ISA_LDSR_MATCH = 16'hA800;
localparam integer ISA_LDSR_RA_HI = 6;
localparam integer ISA_LDSR_RA_LO = 4;

// STSR: 101010001ddd----  (one_slot)
localparam [15:0] ISA_STSR_MASK  = 16'hFF80;
localparam [15:0] ISA_STSR_MATCH = 16'hA880;
localparam integer ISA_STSR_RD_HI = 6;
localparam integer ISA_STSR_RD_LO = 4;

// CRCI: 101011000-------  (one_slot)
localparam [15:0] ISA_CRCI_MASK  = 16'hFF80;
localparam [15:0] ISA_CRCI_MATCH = 16'hAC00;

// STCRC: 101011001ddd----  (one_slot)
localparam [15:0] ISA_STCRC_MASK  = 16'hFF80;
localparam [15:0] ISA_STCRC_MATCH = 16'hAC80;
localparam integer ISA_STCRC_RD_HI = 6;
localparam integer ISA_STCRC_RD_LO = 4;

// CSRR: 10110CCCCCddd---  (one_slot)
localparam [15:0] ISA_CSRR_MASK  = 16'hF800;
localparam [15:0] ISA_CSRR_MATCH = 16'hB000;
localparam integer ISA_CSRR_RD_HI = 5;
localparam integer ISA_CSRR_RD_LO = 3;
localparam integer ISA_CSRR_CSR_HI = 10;
localparam integer ISA_CSRR_CSR_LO = 6;

// CSRW: 10111CCCCCaaa---  (one_slot)
localparam [15:0] ISA_CSRW_MASK  = 16'hF800;
localparam [15:0] ISA_CSRW_MATCH = 16'hB800;
localparam integer ISA_CSRW_CSR_HI = 10;
localparam integer ISA_CSRW_CSR_LO = 6;
localparam integer ISA_CSRW_RA_HI = 5;
localparam integer ISA_CSRW_RA_LO = 3;

// CLR: 11000nnn--------  (one_slot)
localparam [15:0] ISA_CLR_MASK  = 16'hF800;
localparam [15:0] ISA_CLR_MATCH = 16'hC000;
localparam integer ISA_CLR_FLAG_HI = 10;
localparam integer ISA_CLR_FLAG_LO = 8;

// SIG: 11001nnn--------  (one_slot)
localparam [15:0] ISA_SIG_MASK  = 16'hF800;
localparam [15:0] ISA_SIG_MATCH = 16'hC800;
localparam integer ISA_SIG_FLAG_HI = 10;
localparam integer ISA_SIG_FLAG_LO = 8;

// LD: 11010dddaaaiiiii  (one_slot)
localparam [15:0] ISA_LD_MASK  = 16'hF800;
localparam [15:0] ISA_LD_MATCH = 16'hD000;
localparam integer ISA_LD_RD_HI = 10;
localparam integer ISA_LD_RD_LO = 8;
localparam integer ISA_LD_RA_HI = 7;
localparam integer ISA_LD_RA_LO = 5;
localparam integer ISA_LD_IMM_HI = 4;
localparam integer ISA_LD_IMM_LO = 0;

// ST: 11011dddaaaiiiii  (one_slot)
localparam [15:0] ISA_ST_MASK  = 16'hF800;
localparam [15:0] ISA_ST_MATCH = 16'hD800;
localparam integer ISA_ST_RD_HI = 10;
localparam integer ISA_ST_RD_LO = 8;
localparam integer ISA_ST_RA_HI = 7;
localparam integer ISA_ST_RA_LO = 5;
localparam integer ISA_ST_IMM_HI = 4;
localparam integer ISA_ST_IMM_LO = 0;

// CSR numbers
localparam [4:0] CSR_TICK_INT = 5'h00;
localparam [4:0] CSR_TICK_FRAC = 5'h01;
localparam [4:0] CSR_OUTGRP = 5'h02;
localparam [4:0] CSR_INGRP = 5'h03;
localparam [4:0] CSR_BE_CFG = 5'h04;
localparam [4:0] CSR_BE_PINS = 5'h05;
localparam [4:0] CSR_BE_RELOAD = 5'h06;
localparam [4:0] CSR_CRC_POLY = 5'h07;
localparam [4:0] CSR_CRC_INIT = 5'h08;
localparam [4:0] CSR_NOW = 5'h09;
localparam [4:0] CSR_TD = 5'h0A;
localparam [4:0] CSR_FLAGS = 5'h0B;
localparam [4:0] CSR_TID = 5'h0C;
localparam [4:0] CSR_SR = 5'h0D;
localparam [4:0] CSR_CNT = 5'h0E;
localparam [4:0] CSR_CRC = 5'h0F;
localparam [4:0] CSR_OD_MASK = 5'h10;
localparam [4:0] CSR_PIN_OUT = 5'h11;
localparam [4:0] CSR_PIN_OE = 5'h12;
localparam [4:0] CSR_PIN_IN = 5'h13;
localparam [4:0] CSR_SFLAGS = 5'h14;
localparam [4:0] CSR_HOST_IRQ = 5'h15;

// Pin indices
localparam [4:0] PIN_BIDIR0 = 5'd0;
localparam [4:0] PIN_BIDIR1 = 5'd1;
localparam [4:0] PIN_BIDIR2 = 5'd2;
localparam [4:0] PIN_BIDIR3 = 5'd3;
localparam [4:0] PIN_BIDIR4 = 5'd4;
localparam [4:0] PIN_BIDIR5 = 5'd5;
localparam [4:0] PIN_BIDIR6 = 5'd6;
localparam [4:0] PIN_BIDIR7 = 5'd7;
localparam [4:0] PIN_IN0 = 5'd8;
localparam [4:0] PIN_IN1 = 5'd9;
localparam [4:0] PIN_IN2 = 5'd10;
localparam [4:0] PIN_IN3 = 5'd11;
localparam [4:0] PIN_IN4 = 5'd12;
localparam [4:0] PIN_OUT0 = 5'd16;
localparam [4:0] PIN_OUT1 = 5'd17;
localparam [4:0] PIN_OUT2 = 5'd18;
localparam [4:0] PIN_OUT3 = 5'd19;
localparam [4:0] PIN_OUT4 = 5'd20;
localparam [4:0] PIN_OUT5 = 5'd21;

/* verilator lint_on UNUSEDPARAM */
