// GENERATED by tools/loomisa from isa/isa.yaml. DO NOT EDIT.
// ISA version 0.2.0. Purely combinational.
//
// is_<name>    one-hot instruction strobes; all 0 for a reserved word
// is_reserved  no instruction matches (executes as NOP, sets BADOP)
// grp_<class>  OR of the strobes in a class of isa.yaml
// tmg_*        timing class of the matched instruction
// f_<operand>  operand fields moved to a fixed place: imm zero-extended,
//              rel sign-extended to the PC width, 0 when not present
// f_funct      bits of the 'f' sub-operation field (ALU classes)
// csr_<name>   f_csr selects that CSR (qualified by CSRR or CSRW)

`default_nettype none

module loom_decode (
    input  wire [15:0] ir,
    output wire        is_add,
    output wire        is_sub,
    output wire        is_and,
    output wire        is_or,
    output wire        is_xor,
    output wire        is_shl,
    output wire        is_shr,
    output wire        is_ror,
    output wire        is_addi,
    output wire        is_subi,
    output wire        is_andi,
    output wire        is_ori,
    output wire        is_xori,
    output wire        is_shli,
    output wire        is_shri,
    output wire        is_cmpi,
    output wire        is_ldi,
    output wire        is_ldih,
    output wire        is_mov,
    output wire        is_not,
    output wire        is_neg,
    output wire        is_cmp,
    output wire        is_test,
    output wire        is_rev,
    output wire        is_par,
    output wire        is_swap,
    output wire        is_jmp,
    output wire        is_call,
    output wire        is_ret,
    output wire        is_halt,
    output wire        is_bz,
    output wire        is_bnz,
    output wire        is_bc,
    output wire        is_bnc,
    output wire        is_bt,
    output wire        is_bnt,
    output wire        is_djnz,
    output wire        is_jp,
    output wire        is_setp,
    output wire        is_oep,
    output wire        is_out,
    output wire        is_in,
    output wire        is_waitd,
    output wire        is_waitp,
    output wire        is_waite,
    output wire        is_waits,
    output wire        is_waitb,
    output wire        is_dly,
    output wire        is_setd,
    output wire        is_nop,
    output wire        is_push,
    output wire        is_pop,
    output wire        is_sho,
    output wire        is_shi,
    output wire        is_ldsr,
    output wire        is_stsr,
    output wire        is_crci,
    output wire        is_stcrc,
    output wire        is_csrr,
    output wire        is_csrw,
    output wire        is_clr,
    output wire        is_sig,
    output wire        is_ld,
    output wire        is_st,
    output wire        is_reserved,
    output wire        grp_alu,
    output wire        grp_alui,
    output wire        grp_be,
    output wire        grp_branch,
    output wire        grp_csr,
    output wire        grp_fifo,
    output wire        grp_jump,
    output wire        grp_ldi,
    output wire        grp_mem,
    output wire        grp_pin,
    output wire        grp_sflag,
    output wire        grp_unary,
    output wire        grp_wait,
    output wire        tmg_wait,
    output wire        tmg_blocking,
    output wire [2:0]  f_funct,
    output wire [2:0]  f_rd,
    output wire [2:0]  f_ra,
    output wire [2:0]  f_rb,
    output wire [15:0] f_imm,
    output wire [9:0]  f_rel,
    output wire [9:0]  f_abs,
    output wire [4:0]  f_pin,
    output wire        f_val,
    output wire [1:0]  f_edge,
    output wire [2:0]  f_flag,
    output wire        f_tmo,
    output wire [1:0]  f_cond,
    output wire [4:0]  f_csr,
    output wire        csr_tick_int,
    output wire        csr_tick_frac,
    output wire        csr_outgrp,
    output wire        csr_ingrp,
    output wire        csr_be_cfg,
    output wire        csr_be_pins,
    output wire        csr_be_reload,
    output wire        csr_crc_poly,
    output wire        csr_crc_init,
    output wire        csr_now,
    output wire        csr_td,
    output wire        csr_flags,
    output wire        csr_tid,
    output wire        csr_sr,
    output wire        csr_cnt,
    output wire        csr_crc,
    output wire        csr_od_mask,
    output wire        csr_pin_out,
    output wire        csr_pin_oe,
    output wire        csr_pin_in,
    output wire        csr_sflags,
    output wire        csr_host_irq
);

  assign is_add    = (ir & 16'hFE00) == 16'h0000;  // 0000fffdddaaabbb
  assign is_sub    = (ir & 16'hFE00) == 16'h0200;  // 0000fffdddaaabbb
  assign is_and    = (ir & 16'hFE00) == 16'h0400;  // 0000fffdddaaabbb
  assign is_or     = (ir & 16'hFE00) == 16'h0600;  // 0000fffdddaaabbb
  assign is_xor    = (ir & 16'hFE00) == 16'h0800;  // 0000fffdddaaabbb
  assign is_shl    = (ir & 16'hFE00) == 16'h0A00;  // 0000fffdddaaabbb
  assign is_shr    = (ir & 16'hFE00) == 16'h0C00;  // 0000fffdddaaabbb
  assign is_ror    = (ir & 16'hFE00) == 16'h0E00;  // 0000fffdddaaabbb
  assign is_addi   = (ir & 16'hFE00) == 16'h1000;  // 0001fffdddiiiiii
  assign is_subi   = (ir & 16'hFE00) == 16'h1200;  // 0001fffdddiiiiii
  assign is_andi   = (ir & 16'hFE00) == 16'h1400;  // 0001fffdddiiiiii
  assign is_ori    = (ir & 16'hFE00) == 16'h1600;  // 0001fffdddiiiiii
  assign is_xori   = (ir & 16'hFE00) == 16'h1800;  // 0001fffdddiiiiii
  assign is_shli   = (ir & 16'hFE00) == 16'h1A00;  // 0001fffdddiiiiii
  assign is_shri   = (ir & 16'hFE00) == 16'h1C00;  // 0001fffdddiiiiii
  assign is_cmpi   = (ir & 16'hFE00) == 16'h1E00;  // 0001fffdddiiiiii
  assign is_ldi    = (ir & 16'hF800) == 16'h2000;  // 00100dddiiiiiiii
  assign is_ldih   = (ir & 16'hF800) == 16'h2800;  // 00101dddiiiiiiii
  assign is_mov    = (ir & 16'hFE00) == 16'h3000;  // 0011fffdddaaa---
  assign is_not    = (ir & 16'hFE00) == 16'h3200;  // 0011fffdddaaa---
  assign is_neg    = (ir & 16'hFE00) == 16'h3400;  // 0011fffdddaaa---
  assign is_cmp    = (ir & 16'hFE00) == 16'h3600;  // 0011fffdddaaa---
  assign is_test   = (ir & 16'hFE00) == 16'h3800;  // 0011fffdddaaa---
  assign is_rev    = (ir & 16'hFE00) == 16'h3A00;  // 0011fffdddaaa---
  assign is_par    = (ir & 16'hFE00) == 16'h3C00;  // 0011fffdddaaa---
  assign is_swap   = (ir & 16'hFE00) == 16'h3E00;  // 0011fffdddaaa---
  assign is_jmp    = (ir & 16'hFC00) == 16'h4000;  // 010000AAAAAAAAAA
  assign is_call   = (ir & 16'hFC00) == 16'h4400;  // 010001AAAAAAAAAA
  assign is_ret    = (ir & 16'hFC00) == 16'h4800;  // 010010----------
  assign is_halt   = (ir & 16'hFC00) == 16'h4C00;  // 010011----------
  assign is_bz     = (ir & 16'hFF00) == 16'h5000;  // 0101ccc0rrrrrrrr
  assign is_bnz    = (ir & 16'hFF00) == 16'h5200;  // 0101ccc0rrrrrrrr
  assign is_bc     = (ir & 16'hFF00) == 16'h5400;  // 0101ccc0rrrrrrrr
  assign is_bnc    = (ir & 16'hFF00) == 16'h5600;  // 0101ccc0rrrrrrrr
  assign is_bt     = (ir & 16'hFF00) == 16'h5800;  // 0101ccc0rrrrrrrr
  assign is_bnt    = (ir & 16'hFF00) == 16'h5A00;  // 0101ccc0rrrrrrrr
  assign is_djnz   = (ir & 16'hF800) == 16'h6000;  // 01100dddrrrrrrrr
  assign is_jp     = (ir & 16'hF000) == 16'h7000;  // 0111vppppprrrrrr
  assign is_setp   = (ir & 16'hFC00) == 16'h8000;  // 100000vppppp----
  assign is_oep    = (ir & 16'hFC00) == 16'h8400;  // 100001vppppp----
  assign is_out    = (ir & 16'hFC00) == 16'h8800;  // 100010---aaa----
  assign is_in     = (ir & 16'hFC00) == 16'h8C00;  // 100011---ddd----
  assign is_waitd  = (ir & 16'hFE00) == 16'h9000;  // 1001000-iiiiiiii
  assign is_waitp  = (ir & 16'hFE00) == 16'h9200;  // 1001001vpppppT--
  assign is_waite  = (ir & 16'hFE00) == 16'h9400;  // 1001010eepppppT-
  assign is_waits  = (ir & 16'hFE00) == 16'h9600;  // 1001011nnnT-----
  assign is_waitb  = (ir & 16'hFE00) == 16'h9800;  // 1001100ccT------
  assign is_dly    = (ir & 16'hFE00) == 16'h9A00;  // 1001101-iiiiiiii
  assign is_setd   = (ir & 16'hFE00) == 16'h9C00;  // 1001110-iiiiiiii
  assign is_nop    = (ir & 16'hFE00) == 16'h9E00;  // 1001111---------
  assign is_push   = (ir & 16'hFF80) == 16'hA000;  // 101000000aaa----
  assign is_pop    = (ir & 16'hFF80) == 16'hA080;  // 101000001ddd----
  assign is_sho    = (ir & 16'hFF80) == 16'hA400;  // 101001000-------
  assign is_shi    = (ir & 16'hFF80) == 16'hA480;  // 101001001-------
  assign is_ldsr   = (ir & 16'hFF80) == 16'hA800;  // 101010000aaa----
  assign is_stsr   = (ir & 16'hFF80) == 16'hA880;  // 101010001ddd----
  assign is_crci   = (ir & 16'hFF80) == 16'hAC00;  // 101011000-------
  assign is_stcrc  = (ir & 16'hFF80) == 16'hAC80;  // 101011001ddd----
  assign is_csrr   = (ir & 16'hF800) == 16'hB000;  // 10110CCCCCddd---
  assign is_csrw   = (ir & 16'hF800) == 16'hB800;  // 10111CCCCCaaa---
  assign is_clr    = (ir & 16'hF800) == 16'hC000;  // 11000nnn--------
  assign is_sig    = (ir & 16'hF800) == 16'hC800;  // 11001nnn--------
  assign is_ld     = (ir & 16'hF800) == 16'hD000;  // 11010dddaaaiiiii
  assign is_st     = (ir & 16'hF800) == 16'hD800;  // 11011dddaaaiiiii

  assign is_reserved = ~(is_add | is_sub | is_and | is_or | is_xor | is_shl | is_shr | is_ror | is_addi | is_subi | is_andi | is_ori | is_xori | is_shli | is_shri | is_cmpi | is_ldi | is_ldih | is_mov | is_not | is_neg | is_cmp | is_test | is_rev | is_par | is_swap | is_jmp | is_call | is_ret | is_halt | is_bz | is_bnz | is_bc | is_bnc | is_bt | is_bnt | is_djnz | is_jp | is_setp | is_oep | is_out | is_in | is_waitd | is_waitp | is_waite | is_waits | is_waitb | is_dly | is_setd | is_nop | is_push | is_pop | is_sho | is_shi | is_ldsr | is_stsr | is_crci | is_stcrc | is_csrr | is_csrw | is_clr | is_sig | is_ld | is_st);

  assign grp_alu = is_add | is_sub | is_and | is_or | is_xor | is_shl | is_shr | is_ror;
  assign grp_alui = is_addi | is_subi | is_andi | is_ori | is_xori | is_shli | is_shri | is_cmpi;
  assign grp_be = is_sho | is_shi | is_ldsr | is_stsr | is_crci | is_stcrc;
  assign grp_branch = is_bz | is_bnz | is_bc | is_bnc | is_bt | is_bnt | is_djnz | is_jp;
  assign grp_csr = is_csrr | is_csrw;
  assign grp_fifo = is_push | is_pop;
  assign grp_jump = is_jmp | is_call | is_ret | is_halt;
  assign grp_ldi = is_ldi | is_ldih;
  assign grp_mem = is_ld | is_st;
  assign grp_pin = is_setp | is_oep | is_out | is_in;
  assign grp_sflag = is_clr | is_sig;
  assign grp_unary = is_mov | is_not | is_neg | is_cmp | is_test | is_rev | is_par | is_swap;
  assign grp_wait = is_waitd | is_waitp | is_waite | is_waits | is_waitb | is_dly | is_setd | is_nop;
  assign tmg_wait = is_waitd | is_waitp | is_waite | is_waits | is_waitb | is_dly;
  assign tmg_blocking = is_push | is_pop;

  assign f_funct = (is_add | is_sub | is_and | is_or | is_xor | is_shl | is_shr | is_ror | is_addi | is_subi | is_andi | is_ori | is_xori | is_shli | is_shri | is_cmpi | is_mov | is_not | is_neg | is_cmp | is_test | is_rev | is_par | is_swap) ? ir[11:9] : 3'b000;

  assign f_rd = ((is_ldi | is_ldih | is_djnz | is_ld | is_st) ? ir[10:8] : 3'd0)
                | ((is_add | is_sub | is_and | is_or | is_xor | is_shl | is_shr | is_ror | is_addi | is_subi | is_andi | is_ori | is_xori | is_shli | is_shri | is_cmpi | is_mov | is_not | is_neg | is_cmp | is_test | is_rev | is_par | is_swap) ? ir[8:6] : 3'd0)
                | ((is_in | is_pop | is_stsr | is_stcrc) ? ir[6:4] : 3'd0)
                | ((is_csrr) ? ir[5:3] : 3'd0);
  assign f_ra = ((is_ld | is_st) ? ir[7:5] : 3'd0)
                | ((is_out | is_push | is_ldsr) ? ir[6:4] : 3'd0)
                | ((is_add | is_sub | is_and | is_or | is_xor | is_shl | is_shr | is_ror | is_mov | is_not | is_neg | is_cmp | is_test | is_rev | is_par | is_swap | is_csrw) ? ir[5:3] : 3'd0);
  assign f_rb = ((is_add | is_sub | is_and | is_or | is_xor | is_shl | is_shr | is_ror) ? ir[2:0] : 3'd0);
  assign f_imm = ((is_ldi | is_ldih | is_waitd | is_dly | is_setd) ? {8'd0, ir[7:0]} : 16'd0)
                 | ((is_addi | is_subi | is_andi | is_ori | is_xori | is_shli | is_shri | is_cmpi) ? {10'd0, ir[5:0]} : 16'd0)
                 | ((is_ld | is_st) ? {11'd0, ir[4:0]} : 16'd0);
  assign f_rel = ((is_bz | is_bnz | is_bc | is_bnc | is_bt | is_bnt | is_djnz) ? {{2{ir[7]}}, ir[7:0]} : 10'd0)
                 | ((is_jp) ? {{4{ir[5]}}, ir[5:0]} : 10'd0);
  assign f_abs = ((is_jmp | is_call) ? ir[9:0] : 10'd0);
  assign f_pin = ((is_jp) ? ir[10:6] : 5'd0)
                 | ((is_setp | is_oep) ? ir[8:4] : 5'd0)
                 | ((is_waitp) ? ir[7:3] : 5'd0)
                 | ((is_waite) ? ir[6:2] : 5'd0);
  assign f_val = ((is_jp) ? ir[11] : 1'd0)
                 | ((is_setp | is_oep) ? ir[9] : 1'd0)
                 | ((is_waitp) ? ir[8] : 1'd0);
  assign f_edge = ((is_waite) ? ir[8:7] : 2'd0);
  assign f_flag = ((is_clr | is_sig) ? ir[10:8] : 3'd0)
                  | ((is_waits) ? ir[8:6] : 3'd0);
  assign f_tmo = ((is_waitb) ? ir[6] : 1'd0)
                 | ((is_waits) ? ir[5] : 1'd0)
                 | ((is_waitp) ? ir[2] : 1'd0)
                 | ((is_waite) ? ir[1] : 1'd0);
  assign f_cond = ((is_waitb) ? ir[8:7] : 2'd0);
  assign f_csr = ((is_csrr | is_csrw) ? ir[10:6] : 5'd0);

  wire csr_access = is_csrr | is_csrw;
  assign csr_tick_int = csr_access & (f_csr == 5'h00);
  assign csr_tick_frac = csr_access & (f_csr == 5'h01);
  assign csr_outgrp = csr_access & (f_csr == 5'h02);
  assign csr_ingrp = csr_access & (f_csr == 5'h03);
  assign csr_be_cfg = csr_access & (f_csr == 5'h04);
  assign csr_be_pins = csr_access & (f_csr == 5'h05);
  assign csr_be_reload = csr_access & (f_csr == 5'h06);
  assign csr_crc_poly = csr_access & (f_csr == 5'h07);
  assign csr_crc_init = csr_access & (f_csr == 5'h08);
  assign csr_now = csr_access & (f_csr == 5'h09);
  assign csr_td = csr_access & (f_csr == 5'h0A);
  assign csr_flags = csr_access & (f_csr == 5'h0B);
  assign csr_tid = csr_access & (f_csr == 5'h0C);
  assign csr_sr = csr_access & (f_csr == 5'h0D);
  assign csr_cnt = csr_access & (f_csr == 5'h0E);
  assign csr_crc = csr_access & (f_csr == 5'h0F);
  assign csr_od_mask = csr_access & (f_csr == 5'h10);
  assign csr_pin_out = csr_access & (f_csr == 5'h11);
  assign csr_pin_oe = csr_access & (f_csr == 5'h12);
  assign csr_pin_in = csr_access & (f_csr == 5'h13);
  assign csr_sflags = csr_access & (f_csr == 5'h14);
  assign csr_host_irq = csr_access & (f_csr == 5'h15);

endmodule
